### ISSUE TITLE
Blizzard: Patch notes are not being fetched

### ISSUE THREAD

**Issue by HelmicNewciv** [flapjax/FlapJack-Cogs#15]
The bot responds with "I couldn't find any patch notes."  This is true for any game, whether or not the bot was online when new patch notes were posted.

**Comment by flapjax** [comment]
Thanks, this entire cog has been due for a rework pretty much since I released it. See issue #2. I plan on:

- Removing Pandoc requirement entirely.
- Instead of posting the entire notes in chat, just post a link, or the first couple lines of the patch notes + a link to the full notes.
- Add autodetection of new patch notes, with the option to post an alert in the channel when this happens (sort of like a webhook, in fact I should check to see if a suitable webhook already exists)

Thoughts?

**Comment by HelmicNewciv** [comment]
Yep, it was the missing Pandoc dependency.  Those sound like fine ideas, though it'd definitely be helpful to post the entirety of the patch notes if they're very brief (one or two changes or a bugfix).  Links to prior patch notes would also be helpful as sometimes Blizzard will put out a lot of patches in quick succession.

The ability to specify between PTR and live patchnotes would also be helpful, for example checking out the recent Lucio changes on the Overwatch PTR.

**Comment by flapjax** [comment]
Rework is complete. Pandoc is no longer required, and patch notes are working again (at least for all current notes -- please let me know if you encounter future patch notes that aren't working). I will add PTR notes to my roadmap, it's a good idea 👌
