### ISSUE TITLE
Colorme allows for role escalation

### ISSUE THREAD

**Issue by HelmicNewciv** [flapjax/FlapJack-Cogs#24]
The way Discord role logic works, your very highest role, regardless of permission, determines your ability to kick, ban, or modify roles.  This allows users who apply color roles to be able to kick, ban, or modify the permissions of others based on when they added roles.

For flat hierarchy servers like mine where everyone is able to kick/ban randoms to avoid issues with spambots, this means my regular members could kick or ban each other.  For more traditional servers, this would allow mods to demote one another or promote someone else to mod.  They can even modify their own color permission if they have a low-ranking modify roles permission, then when they're demoted they can sneakily keep all their old permissions.

There's no two ways about it now, color roles _must_ go at the very bottom and that's assuming that @ everyone doesn't have any weird permissions.

**Comment by flapjax** [comment]
This has always been the behavior of the cog. That's why I tried to plaster it with warnings explaining how it worked, and I only recommend it be used on small private servers, when permissions and role hierarchy don't really matter.

But, I think you've provided a good enough argument for attempting the switch. If colored roles have the ability to "show through" higher colorless roles, then I can think of no good reason the cog should continue enforcing the top role as the colored role. The switch will be a breaking change, but I think we can all deal with the minor inconvenience of re-setting up our roles, and in return we will get a cog that is more secure and usable by a wider audience. 

With this change, I will also feel comfortable having the option to add 8 or 16 default colored roles that can be used by multiple people, which would open this cog up to large servers. Stay tuned...

**Comment by flapjax** [comment]
Closing, as this should be fixed now :)

Please reopen if you encounter further problems with the updated version.
