### ISSUE TITLE
[sfx] Hijacking/skip exploit

### ISSUE THREAD

**Issue by CRASNY** [flapjax/FlapJack-Cogs#28]
There's currently an interaction between sfx.py and audio.py where you can bypass the percentage-based skip vote in audio.py when a song is playing by entering another channel, playing a sound with sfx.py, and inputting the skip command. The song will auto-skip because you've hijacked the bot into another channel as the only person.

**Comment by flapjax** [comment]
Unfortunately I cannot give an ETA for a patch that will address this. The way I see it, there are two options:

- limit channel changes while Audio is playing
- interfere with Audio cog to block/change a skip vote

I am not too keen on the first, because I think it defeats one of the coolest capabilities demonstrated by this cog, the ability to hop channel to channel to process a sound effect queue, even in the middle of music.

I am not too keen on the second because with Red Audio being in the middle of a rewrite, *and* the Discord API python wrapper in the middle of a huge rewrite, which includes an audio overhaul, it doesn't make a lot of sense to sink time into patching this cog to work with our current setup.

So I hope this makes sense. I will leave this issue open, because it is legitimate, and I would like to see what information comes out of the rewrite efforts in the next few weeks. The most likely short term solution would be adding an *optional* setting to limit channel changes while music is playing. If anyone has other suggestions, I'm all ears 👂

**Comment by CRASNY** [comment]
I completely agree with the solution of limiting channel changes while Audio is playing. That seems to be a bit of a problem within itself, even more so compounded with this skip exploit.

**Comment by aikaterna** [comment]
This issue will not be fixed as v2 is dead, and even if you do get v2 to connect to Discord's API... voice is pretty broken besides that. Closing this as SFX will not be on this repo for v3.
